
name: Build

on:
  workflow_dispatch:



jobs:

  build:
    runs-on: ubuntu-latest
    environment: dev
        

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Image
        run: |
          cd app
          docker build -t peteracr007.azurecr.io/app-node .
          docker image ls
    
      - name: Scan Image
        uses: crazy-max/ghaction-container-scan@v3
        with:
          image: peteracr007.azurecr.io/app-node:latest
